const mockData = {
  profile: {
    user_id: 'brikeld_001',
    username: 'Brikeld Hoxha',
    profile_picture: 'profile.jpg',
    dominantPersona: 'security',
    status: 'online',
    last_activity: '3d & 8 hours ago',
    account_created: '2024-06-15',
    device_name: "Brikeld's MacBook Pro",
  },
  scores: {
    overall: 68,
    productivity: 72,
    security: 85,
    social: 45,
    trend: '+5%',
    rank_position: 1847,
    rank_total: 12450,
  },
  identity: {
    device: {
      model: 'MacBook Pro',
      macos_version: '26.0',
      hostname: "Brikeld's MacBook Pro",
    },
    location_inferred: 'Geneva, Switzerland',
    languages: ['en-CH', 'de-CH', 'fr-CH', 'it-CH'],
    ui_theme: 'Dark Mode',
    screen_resolution: '3024 x 1964 Retina',
  },
  activity: {
    peak_hours: {
      primary: '10 PM - 2 AM',
      secondary: '2 PM - 4 PM',
    },
    most_active_day: 'Thursday',
    days_order: ['Thursday', 'Tuesday', 'Wednesday', 'Friday', 'Monday', 'Saturday', 'Sunday'],
    sleep_pattern: 'Night Owl (Late-night coding detected)',
    uptime: '1 day',
    current_status: 'Active (machine awake for 46 mins)',
  },
  tech_stack: {
    primary_apps: [
      { name: 'Adobe Premiere Pro 2025', category: 'video' },
      { name: 'Adobe Photoshop 2025', category: 'design' },
      { name: 'Visual Studio Code', category: 'development' },
      { name: 'Blender 4.5.3 LTS', category: '3d' },
      { name: 'Figma', category: 'design' },
      { name: 'Google Chrome', category: 'browser' },
    ],
    ai_tools: ['Claude', 'ChatGPT', 'Cursor'],
    design_tools_count: 12,
    total_apps_installed: 60,
    languages_detected: ['JavaScript/JSX', 'Python', 'HTML/CSS'],
    vcs: 'GitHub Desktop',
  },
  network: {
    wifi_networks_recent: [
      'ECALNET',
      'FibreBox_X6-002887',
      'TP-Link_D58C',
      'eduroam',
      'Ginevra Cafe',
      'Vodafone-C49410867',
    ],
    vpn_detected: 'NordVPN',
    open_ports: ['*.3001', '*.8021', '127.0.0.1.5173'],
    connectivity_status: 'Active',
  },
  content: {
    creator_files_sample: ['App.jsx', 'ProfileHeader.jsx', 'harvesters_enhanced.py', 'PERSONA_SCORING_SPEC.md'],
    consumer_files_sample: ['profile.jpg', 'Dreams.jpg', 'E_sempre_bello.jpg', 'what i want.png'],
    files_modified_7days: 80,
    creator_consumer_ratio: '35% creator / 65% consumer',
  },
  storage: {
    total_gb: 994.7,
    used_gb: 337.1,
    free_gb: 657.6,
    usage_percent: 33.9,
    battery_percent: 73,
    battery_condition: 'Normal',
    battery_health_percent: 95,
  },
  security: {
    sip: { status: 'Enabled', icon: '✓' },
    filevault: { status: 'On', icon: '✓' },
    gatekeeper: { status: 'Enabled', icon: '✓' },
    pending_updates: 'macOS 26.4.1 (security)',
    crash_reports_7days: 0,
    disk_smart_status: 'Verified',
  },
  behavioral: {
    profile_type: 'Developer/Designer',
    badges: ['Night Owl 🦉', 'Code Warrior ⚔️', 'Creative Professional 🎨'],
    inferred_role: 'Creative Developer/Designer Student',
    school_detected: "ECAL (École Cantonale d'Art de Lausanne)",
    work_context: 'Freelance/Student Projects',
  },
  lifestyle: {
    entertainment_apps: ['Spotify', 'DAZN', 'Stremio', 'Discord'],
    health_tracking: ['TrackWeight', 'WattsConnected'],
    gaming: ['Epic Games Launcher'],
    last_music_activity: '2026-04-27 10:48',
  },
};

export default mockData;
